# Generated by Django 4.2.17 on 2025-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='educational_resources/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
