# Generated by Django 4.2.17 on 2025-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_healthresource_alter_educationalresource_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('support', 'Support Group'), ('social', 'Social Event'), ('professional', 'Professional Network')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('contact_info', models.EmailField(max_length=254)),
            ],
        ),
    ]
